# Generated by Django 4.1.7 on 2023-04-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=250)),
                ('blog_img', models.ImageField(upload_to='blog/images')),
                ('content', models.TextField()),
                ('pub_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
