# Generated by Django 4.1.7 on 2023-06-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
