# Generated by Django 4.1.7 on 2023-07-08 07:52

import django.contrib.postgres.fields
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact_message_contact_subject_alter_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=255)),
                ('phone_no', models.IntegerField()),
                ('date', models.DateField()),
                ('department', models.TextField()),
                ('doctor', models.TextField()),
                ('message', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='message',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='appointment',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='appointment',
            name='communication_mode',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='expectations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=home.models.get_default_array, size=None),
        ),
        migrations.AddField(
            model_name='appointment',
            name='financial_status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='having_chronic_pain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_anxious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_religious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_spritual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='language',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='mark_that_apply',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=home.models.get_default_array, size=None),
        ),
        migrations.AddField(
            model_name='appointment',
            name='preferences',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='relationship_status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='religious_status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='resources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=home.models.get_default_array, size=None),
        ),
        migrations.AddField(
            model_name='appointment',
            name='sex',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='taken_therapy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='taking_medications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='therapy_reason',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=home.models.get_default_array, size=None),
        ),
        migrations.AddField(
            model_name='appointment',
            name='type_of_therapy',
            field=models.CharField(default='', max_length=50),
        ),
    ]
