# Generated by Django 4.2.3 on 2023-07-15 10:56

import django.contrib.postgres.fields
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_shortappointment_remove_appointment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counseller_experience', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=home.models.get_default_array, size=None)),
                ('Additional_focus_areas', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=home.models.get_default_array, size=None)),
                ('additional_details', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
