# Generated by Django 4.1.7 on 2023-07-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pass_token',
            field=models.CharField(default='', max_length=150),
        ),
    ]
