# Generated by Django 4.1.7 on 2023-08-05 06:49

import django.contrib.postgres.fields
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_profile_pass_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment2',
        ),
        migrations.AddField(
            model_name='appointment',
            name='Additional_focus_areas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=home.models.get_default_array, size=None),
        ),
        migrations.AddField(
            model_name='appointment',
            name='additional_details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='counseller_experience',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=home.models.get_default_array, size=None),
        ),
    ]
