# Generated by Django 4.1.7 on 2023-08-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_profile_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='apt_token',
            field=models.CharField(default='', max_length=150),
        ),
    ]
